version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: jakeybot_mongodb
    volumes:
      - ./mongodb:/data/db
    env_file:
      - .env
    ports:
      - "27017:27017"

  jakeybot:
    image: zavocc/jakey:sugilite
    container_name: jakeybot
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - "2222:2222"

volumes:
  mongodb_data:

